### ISSUE TITLE
Let the user decide output data format

### ISSUE THREAD

**Issue by ale0xb** [martgnz/es-atlas#6]
Topo or geojson (or both!)

**Comment by martgnz** [comment]
I could try to make this work but I don't think we should add more functionality without a real usecase. Do you actually need a GeoJSON file? This is mostly aimed to make cartography ready for D3. QGIS can read TopoJSON too.

I somewhat struggle to see the benefits for this because GeoJSON doesn't support multiple objects in the same file, is less efficient, etc. And there is another project that [provides](https://github.com/codeforspain/ds-limites-administrativos/tree/master/data) reusable files in this format (albeit they seem to be outdated).

Sorry but closing this for now if there's not a pressing need for them.
